name: smart_shopper2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0        # State Management (BLoC Pattern)
  equatable: ^2.0.5         # Value equality for BLoC states/events
  objectbox: ^4.0.3         # ObjectBox core database library
  objectbox_flutter_libs: ^4.0.3 # ObjectBox native libraries (runtime dependency)
  path_provider: ^2.1.3     # Find filesystem paths (used by ObjectBox)
  path: ^1.9.0              # Path manipulation (used with path_provider)
  get_it: ^8.0.3            # Service Locator for Dependency Injection
  go_router: ^14.1.0        # Declarative Routing/Navigation
  url_launcher: ^6.3.0      # Launch URLs (websites, phone calls)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11        # Code generation tool runner
  objectbox_generator: ^4.0.3 # Generates ObjectBox binding code


flutter:
  uses-material-design: true
