name: smart_shopper
description: A shopping list management application
version: 1.0.0+1  # format is version_name+version_code

# Add some important categories for the store
# Consider adding relevant categories
category: PRODUCTIVITY

# Update author info
#homepage: https://your-website.com
#repository: https://github.com/your-username/smart_shopper

publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0        # State Management (BLoC Pattern)
  equatable: ^2.0.5         # Value equality for BLoC states/events
  objectbox: ^4.0.3         # ObjectBox core database library
  objectbox_flutter_libs: ^4.0.3 # ObjectBox native libraries (runtime dependency)
  path_provider: ^2.1.3     # Find filesystem paths (used by ObjectBox)
  path: ^1.9.0              # Path manipulation (used with path_provider)
  get_it: ^8.0.3            # Service Locator for Dependency Injection
  go_router: ^15.1.3        # Declarative Routing/Navigation
  url_launcher: ^6.3.0      # Launch URLs (websites, phone calls)
  cupertino_icons: ^1.0.6
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11        # Code generation tool runner
  objectbox_generator: ^4.0.3 # Generates ObjectBox binding code

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true  # Generate Android icons
  ios: false     # No iOS icons for now
  remove_alpha_ios: true  # Remove transparency for iOS icons
  image_path: "assets/icons/app_icon.png"  # Path to your icon file
  adaptive_icon_background: "#FFFFFF"  # Background color for adaptive icons
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"  # Foreground for adaptive icons (can be same as main icon)
