import 'package:objectbox/objectbox.dart';
// This imports the generated file that contains the openStore() function
// and entity model definitions for ObjectBox.
import 'objectbox.g.dart'; 
// Import your models barrel file to make model types known.
import 'models/models.dart';

/// A helper class to manage the ObjectBox store and provide access to entity boxes.
class ObjectBoxHelper {
  /// The ObjectBox store instance.
  late final Store _store;

  // Declare Box instances for each of your entities.
  // These will be initialized in the _create private constructor.
  late final Box<Brand> brandBox;
  late final Box<PriceEntry> priceEntryBox;
  late final Box<GroceryStore> groceryStoreBox;
  late final Box<ShoppingItem> shoppingItemBox;
  late final Box<ShoppingList> shoppingListBox;

  /// Private constructor to initialize the store and boxes.
  /// This is called by the static `create` method.
  ObjectBoxHelper._create(this._store) {
    // Initialize all your entity boxes here
    brandBox = _store.box<Brand>();
    priceEntryBox = _store.box<PriceEntry>();
    groceryStoreBox = _store.box<GroceryStore>();
    shoppingItemBox = _store.box<ShoppingItem>();
    shoppingListBox = _store.box<ShoppingList>();
  }

  /// Creates and initializes an ObjectBoxHelper instance.
  /// 
  /// This static method should be called once at app startup (e.g., in main.dart)
  /// to set up the database.
  static Future<ObjectBoxHelper> create() async {
    // The openStore() function is generated by ObjectBox (in objectbox.g.dart)
    // and opens the database, creating it if it doesn't exist.
    final store = await openStore();
    return ObjectBoxHelper._create(store);
  }
}
